openapi: 3.0.4

info:
  title: Okestro API
  description: 오케스트로 API
  version: 1.0.0

servers:
  - url: http://34.64.212.207:8080/api/v1
    description: Local GCP 서버

tags:
  - name: okestro
    description: 오케스트로 사원 API
  - name: oke-cloud
    description: 오케스트로 클라우드 사원 API

paths:
  /okestro/user:
    get:
      tags:
       - okestro
      summary: 오케스트로 전체 사원 조회
      description: 오케스트로의 모든 사원를 리스트 형태로 조회합니다.
      operationId: getOkestroUsers
      responses:
        '200':
          description: 오케스트로 사원 리스트 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OkestroUser'
        '400':
          description: 잘못된 요청
        '404':
          description: 정보가 없습니다.
        '500':
          description: 서버 에러
        default:
          description: 알 수 없는 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - okestroAuth:
          - read:okestro
          - write:okestro
    
    post:
      tags:
       - okestro
      summary: 오케스트로 사원 추가
      description: 오케스트로에 사원를 추가합니다.
      operationId : insertOkestroUsers
      requestBody:
        description: 추가할 오케스트로 사원 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OkestroUser'
        required: true
      responses:
        '200':
          description: 오케스트로 사원 추가 성공
        '400':
          description: 잘못된 요청
        '404':
          description: 정보가 없습니다.
        '500':
          description: 서버 에러
        default:
          description: 알 수 없는 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    put:
      tags:
      - okestro
      summary: 오케스트로 사원 정보 수정
      description: 오케스트로 사원 1명의 정보를 수정합니다.
      operationId: updateOkestroUsers
      requestBody:
        description: 수정할 오케스트로 사원 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OkestroUser'
        required: true
      responses:
        '200':
          description: 오케스트로 사원 정보 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkestroUser'
        '400':
          description: 잘못된 요청
        '404':
          description: 정보가 없습니다.
        '500':
          description: 서버 에러
        default:
          description: 알 수 없는 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /okestro/user/{userId}:
    get:
      tags:
       - okestro
      summary: 오케스트로 사원 상세 조회
      description: 오케스트로 사원 1명의 정보를 조회합니다.
      operationId: getOkestroUserInfo
      parameters:
        - name: userId
          in: path
          description: 오케스트로 사원 ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 오케스트로 사원 정보 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkestroUser'
        '400':
          description: 잘못된 ID
        '404':
          description: 존재하지 않는 ID
        default:
          description: 알 수 없는 에러
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
    
    delete:
      tags:
      - okestro
      summary: 오케스트로 사원 정보 삭제
      description: 오케스트로 사원 1명의 정보를 삭제합니다.
      operationId: deleteOkestroUserInfo
      parameters:
        - name: userId
          in: path
          description: 삭제할 오케스트로 사원 ID
          required: true
          schema:
            format: int64
          example: 3
      responses:
        '200':
          description: 오케스트로 사원 정보 삭제 성공
        '400':
          description: 잘못된 요청
        '404':
          description: 정보가 없습니다.
        '500':
          description: 서버 에러
        default:
          description: 알 수 없는 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      
    
          
  /oke-cloud/member:
    get:
      tags:
       - oke-cloud
      summary: 오케스트로 클라우드 전체 사원 조회
      description: 오케스트로 클라우드의 모든 사원를 리스트 형태로 조회합니다.
      operationId: getOkeCloudUsers
      responses:
        '200':
          description: 오케스트로 클라우드 사원 리스트 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OkeCloudUser'
        '400':
          description: 잘못된 요청
        '404':
          description: 정보가 없습니다.
        '500':
          description: 서버 에러
        default:
          description: 알 수 없는 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    OkestroUser:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          description: 유니크한 사원의 식별자
          example: 4
        name:
          type: string
          description: 사원의 이름
          example: 김지헌
        email:
          type: string
          format: email
          description: 사원의 이메일 주소
          example: okejhk@okestro.com
        created_at:
          type: string
          format: date-time
          description: 사원 생성 시간
          
    OkeCloudUser:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          description: 유니크한 사원의 식별자
          example: 4
        name:
          type: string
          description: 사원의 이름
          example: 홍길동
        email:
          type: string
          format: email
          description: 사원의 이메일 주소
          example: okehgd@okecloud.com
        created_at:
          type: string
          format: date-time
          description: 사원 생성 시간

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: 에러 코드
        message:
          type: string
          description: 에러 메세지
      required:
        - code
        - message

  securitySchemes:
    okestroAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://34.64.212.207:8080/oauth/authorize
          scopes:
            "write:okestro": 오케스트로 사원 변경 권한
            "read:okestro": 오케스트로 사원 조회 권한